#!/bin/sh

updatePullRequest() {
    echo "this is a new func"
    url="/repos/$owner/$repo/pulls/$pull_number"
    body="{\"body\": \"\"}"
}

prettypull() {
    BASE_BRANCH=$1
    FEATURE_BRANCH=$2
    success=true

    if [ -z "$BASE_BRANCH" ]; then
        BASE_BRANCH=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f 2 | awk '{$1=$1};1')
        echo "No base branch provided. Using remote default branch ${BASE_BRANCH}"
    fi

    if [ -z "$FEATURE_BRANCH" ]; then
        FEATURE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "No feature branch provided. Using current branch ${FEATURE_BRANCH}"
    fi

    echo "Opening pull request from ${FEATURE_BRANCH} to ${BASE_BRANCH}"
    pr_body="${FEATURE_BRANCH} => ${BASE_BRANCH}\n\n$(git log --pretty=format:"## %s\n\n%b\n\n%H \n\n---\n" --reverse --no-merges "$BASE_BRANCH"..."$FEATURE_BRANCH")"
    printf "$pr_body" | hub pull-request --base "$BASE_BRANCH" --head "$FEATURE_BRANCH" --file=- || sucess=false

    if [ $success != true ]; then
        current_pr_url=$(hub pr list -f %U -h "$FEATURE_BRANCH")

        if [ -z $url ]; then
            echo "Unable to open a pull-request ¯\_(ツ)_/¯"
            return 1
        fi

        echo "There is already a PR open: $current_pr_url"
        printf "$pr_body"
        # printf "$pr_body" | hub api "$url" --input=-
    fi
}
