#!/usr/bin/env bash

function prettify-commits {
    BASE_BRANCH=$1
    FEATURE_BRANCH=$2

    msg="$FEATURE_BRANCH => $BASE_BRANCH\n\n"

    diff_commit_shas=$(git log --pretty="%H" --no-merges $BASE_BRANCH...$FEATURE_BRANCH)
    for commit_sha in $diff_commit_shas
    do
        msg="${msg}$(git log --pretty=format:"## %s\n\n%b\n\n%H \n\n---\n" -1 $commit_sha)"
    done
    echo -e $msg
}

function pretty-pull {
    BASE_BRANCH=$1
    FEATURE_BRANCH=$2

    if [ -z $FEATURE_BRANCH ]; then
        FEATURE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    fi

    echo "Opening pull request from ${FEATURE_BRANCH} to ${BASE_BRANCH}"

    prettify-commits $BASE_BRANCH $FEATURE_BRANCH | hub pull-request --file=-
}
