on: ['pull_request']

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Run shellcheck on them scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: azohra/shell-linter@v0.3.0
        with:
          path: '*.sh'
